---
language: node_js
node_js:
  - '10'

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

stages:
  - build
  - name: deploy
    if: branch = master AND type = push

jobs:
  fail_fast: true
  include:
    - stage: build
      name: build
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH

      install:
        - yarn install --non-interactive

      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn lint:md
        - yarn test

    - stage: deploy
      script: yarn semantic-release
